# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pypcga-fe.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.Module1Frame = QtWidgets.QFrame(self.centralwidget)
        self.Module1Frame.setGeometry(QtCore.QRect(20, 60, 361, 101))
        self.Module1Frame.setAutoFillBackground(True)
        self.Module1Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Module1Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Module1Frame.setObjectName("Module1Frame")
        self.label_2 = QtWidgets.QLabel(self.Module1Frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.Module1Frame)
        self.textEdit.setGeometry(QtCore.QRect(40, 6, 61, 21))
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(self.Module1Frame)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.Module1Frame)
        self.textEdit_2.setGeometry(QtCore.QRect(40, 30, 61, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_4 = QtWidgets.QLabel(self.Module1Frame)
        self.label_4.setGeometry(QtCore.QRect(110, 10, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textEdit_3 = QtWidgets.QTextEdit(self.Module1Frame)
        self.textEdit_3.setGeometry(QtCore.QRect(140, 6, 61, 21))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_5 = QtWidgets.QLabel(self.Module1Frame)
        self.label_5.setGeometry(QtCore.QRect(110, 30, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.textEdit_4 = QtWidgets.QTextEdit(self.Module1Frame)
        self.textEdit_4.setGeometry(QtCore.QRect(140, 30, 61, 21))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_6 = QtWidgets.QLabel(self.Module1Frame)
        self.label_6.setGeometry(QtCore.QRect(210, 10, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.textEdit_5 = QtWidgets.QTextEdit(self.Module1Frame)
        self.textEdit_5.setGeometry(QtCore.QRect(240, 6, 61, 21))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.Module1Frame)
        self.textEdit_6.setGeometry(QtCore.QRect(240, 30, 61, 21))
        self.textEdit_6.setObjectName("textEdit_6")
        self.label_7 = QtWidgets.QLabel(self.Module1Frame)
        self.label_7.setGeometry(QtCore.QRect(210, 30, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.Module1Frame)
        self.label_9.setGeometry(QtCore.QRect(10, 60, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.textEdit_7 = QtWidgets.QTextEdit(self.Module1Frame)
        self.textEdit_7.setGeometry(QtCore.QRect(60, 60, 241, 21))
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 210, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setObjectName("label_8")
        self.Module1Frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.Module1Frame_2.setGeometry(QtCore.QRect(20, 250, 361, 101))
        self.Module1Frame_2.setAutoFillBackground(True)
        self.Module1Frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Module1Frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Module1Frame_2.setObjectName("Module1Frame_2")
        self.label_10 = QtWidgets.QLabel(self.Module1Frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.textEdit_8 = QtWidgets.QTextEdit(self.Module1Frame_2)
        self.textEdit_8.setGeometry(QtCore.QRect(130, 10, 211, 21))
        self.textEdit_8.setObjectName("textEdit_8")
        self.label_11 = QtWidgets.QLabel(self.Module1Frame_2)
        self.label_11.setGeometry(QtCore.QRect(10, 30, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.textEdit_9 = QtWidgets.QTextEdit(self.Module1Frame_2)
        self.textEdit_9.setGeometry(QtCore.QRect(40, 30, 301, 21))
        self.textEdit_9.setObjectName("textEdit_9")
        self.label_16 = QtWidgets.QLabel(self.Module1Frame_2)
        self.label_16.setGeometry(QtCore.QRect(10, 60, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.textEdit_14 = QtWidgets.QTextEdit(self.Module1Frame_2)
        self.textEdit_14.setGeometry(QtCore.QRect(60, 60, 241, 21))
        self.textEdit_14.setObjectName("textEdit_14")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menupyPCGA = QtWidgets.QMenu(self.menubar)
        self.menupyPCGA.setObjectName("menupyPCGA")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionDownload = QtWidgets.QAction(MainWindow)
        self.actionDownload.setObjectName("actionDownload")
        self.menupyPCGA.addAction(self.actionNew)
        self.menupyPCGA.addAction(self.actionSave)
        self.menupyPCGA.addAction(self.actionDownload)
        self.menubar.addAction(self.menupyPCGA.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Module 1"))
        self.label_2.setText(_translate("MainWindow", "Lx:"))
        self.label_3.setText(_translate("MainWindow", "dx:"))
        self.label_4.setText(_translate("MainWindow", "Ly:"))
        self.label_5.setText(_translate("MainWindow", "dy:"))
        self.label_6.setText(_translate("MainWindow", "Lz:"))
        self.label_7.setText(_translate("MainWindow", "dz:"))
        self.label_9.setText(_translate("MainWindow", "s_true:"))
        self.label_8.setText(_translate("MainWindow", "Module 2"))
        self.label_10.setText(_translate("MainWindow", "forward_model:"))
        self.label_11.setText(_translate("MainWindow", "log:"))
        self.label_16.setText(_translate("MainWindow", "s_true:"))
        self.menupyPCGA.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionDownload.setText(_translate("MainWindow", "Download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

