# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pypcga-fe-2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget
import matplotlib
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy.io import savemat, loadmat
import numpy as np
import math


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 855)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(730, 20, 701, 511))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(730, 545, 701, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.export_settings = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.export_settings.setFont(font)
        self.export_settings.setObjectName("export_settings")
        self.gridLayout_6.addWidget(self.export_settings, 0, 1, 1, 1)
        self.import_settings = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.import_settings.setFont(font)
        self.import_settings.setObjectName("import_settings")
        self.gridLayout_6.addWidget(self.import_settings, 0, 2, 1, 1)
        self.execute_button = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.execute_button.setFont(font)
        self.execute_button.setObjectName("execute_button")
        self.gridLayout_6.addWidget(self.execute_button, 0, 0, 1, 1)
        #added
        self.execute_button.clicked.connect(self.execute)

        self.progress_bar_label = QtWidgets.QLabel(self.centralwidget)
        self.progress_bar_label.setGeometry(QtCore.QRect(11, 11, 76, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.progress_bar_label.setFont(font)
        self.progress_bar_label.setObjectName("progress_bar_label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(11, 33, 681, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.fname_label = QtWidgets.QLabel(self.centralwidget)
        self.fname_label.setGeometry(QtCore.QRect(11, 60, 63, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.fname_label.setFont(font)
        self.fname_label.setObjectName("fname_label")
        self.dimension_label = QtWidgets.QLabel(self.centralwidget)
        self.dimension_label.setGeometry(QtCore.QRect(569, 60, 72, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.dimension_label.setFont(font)
        self.dimension_label.setObjectName("dimension_label")
        self.dim_box = QtWidgets.QSpinBox(self.centralwidget)
        self.dim_box.setGeometry(QtCore.QRect(651, 60, 39, 24))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.dim_box.setFont(font)
        self.dim_box.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.dim_box.setMaximum(0)
        self.dim_box.setObjectName("dim_box")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(11, 94, 217, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.Module1Frame = QtWidgets.QFrame(self.centralwidget)
        self.Module1Frame.setGeometry(QtCore.QRect(11, 114, 691, 181))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.Module1Frame.setFont(font)
        self.Module1Frame.setAutoFillBackground(True)
        self.Module1Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Module1Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Module1Frame.setObjectName("Module1Frame")
        self.gridLayout = QtWidgets.QGridLayout(self.Module1Frame)
        self.gridLayout.setObjectName("gridLayout")
        self.x0_label = QtWidgets.QLabel(self.Module1Frame)
        self.x0_label.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.x0_label.setFont(font)
        self.x0_label.setObjectName("x0_label")
        self.gridLayout.addWidget(self.x0_label, 0, 0, 1, 1)
        self.x0_box = QtWidgets.QTextEdit(self.Module1Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x0_box.sizePolicy().hasHeightForWidth())
        self.x0_box.setSizePolicy(sizePolicy)
        self.x0_box.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.x0_box.setFont(font)
        self.x0_box.setAcceptDrops(True)
        self.x0_box.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.x0_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.x0_box.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.x0_box.setTabStopWidth(5)
        self.x0_box.setObjectName("x0_box")
        self.gridLayout.addWidget(self.x0_box, 0, 1, 1, 1)
        self.y0_label = QtWidgets.QLabel(self.Module1Frame)
        self.y0_label.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.y0_label.setFont(font)
        self.y0_label.setObjectName("y0_label")
        self.gridLayout.addWidget(self.y0_label, 0, 2, 1, 1)
        self.y0_box = QtWidgets.QTextEdit(self.Module1Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y0_box.sizePolicy().hasHeightForWidth())
        self.y0_box.setSizePolicy(sizePolicy)
        self.y0_box.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.y0_box.setFont(font)
        self.y0_box.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.y0_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.y0_box.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.y0_box.setObjectName("y0_box")
        self.gridLayout.addWidget(self.y0_box, 0, 3, 1, 1)
        self.z0_label = QtWidgets.QLabel(self.Module1Frame)
        self.z0_label.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.z0_label.setFont(font)
        self.z0_label.setObjectName("z0_label")
        self.gridLayout.addWidget(self.z0_label, 0, 4, 1, 1)
        self.z0_box = QtWidgets.QTextEdit(self.Module1Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z0_box.sizePolicy().hasHeightForWidth())
        self.z0_box.setSizePolicy(sizePolicy)
        self.z0_box.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.z0_box.setFont(font)
        self.z0_box.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.z0_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.z0_box.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.z0_box.setObjectName("z0_box")
        self.gridLayout.addWidget(self.z0_box, 0, 5, 1, 1)
        self.lx_label = QtWidgets.QLabel(self.Module1Frame)
        self.lx_label.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.lx_label.setFont(font)
        self.lx_label.setObjectName("lx_label")
        self.gridLayout.addWidget(self.lx_label, 1, 0, 1, 1)
        self.lx_box = QtWidgets.QTextEdit(self.Module1Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lx_box.sizePolicy().hasHeightForWidth())
        self.lx_box.setSizePolicy(sizePolicy)
        self.lx_box.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.lx_box.setFont(font)
        self.lx_box.setAcceptDrops(True)
        self.lx_box.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lx_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lx_box.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lx_box.setTabStopWidth(5)
        self.lx_box.setObjectName("lx_box")
        self.gridLayout.addWidget(self.lx_box, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.Module1Frame)
        self.label_4.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.ly_box = QtWidgets.QTextEdit(self.Module1Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ly_box.sizePolicy().hasHeightForWidth())
        self.ly_box.setSizePolicy(sizePolicy)
        self.ly_box.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.ly_box.setFont(font)
        self.ly_box.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.ly_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ly_box.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ly_box.setObjectName("ly_box")
        self.gridLayout.addWidget(self.ly_box, 1, 3, 1, 1)
        self.lz_label = QtWidgets.QLabel(self.Module1Frame)
        self.lz_label.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.lz_label.setFont(font)
        self.lz_label.setObjectName("lz_label")
        self.gridLayout.addWidget(self.lz_label, 1, 4, 1, 1)
        self.lz_box = QtWidgets.QTextEdit(self.Module1Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lz_box.sizePolicy().hasHeightForWidth())
        self.lz_box.setSizePolicy(sizePolicy)
        self.lz_box.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.lz_box.setFont(font)
        self.lz_box.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lz_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lz_box.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lz_box.setObjectName("lz_box")
        self.gridLayout.addWidget(self.lz_box, 1, 5, 1, 1)
        self.dxx_label = QtWidgets.QLabel(self.Module1Frame)
        self.dxx_label.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.dxx_label.setFont(font)
        self.dxx_label.setObjectName("dxx_label")
        self.gridLayout.addWidget(self.dxx_label, 2, 0, 1, 1)
        self.dxx_box = QtWidgets.QTextEdit(self.Module1Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dxx_box.sizePolicy().hasHeightForWidth())
        self.dxx_box.setSizePolicy(sizePolicy)
        self.dxx_box.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.dxx_box.setFont(font)
        self.dxx_box.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.dxx_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dxx_box.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dxx_box.setObjectName("dxx_box")
        self.gridLayout.addWidget(self.dxx_box, 2, 1, 1, 1)
        self.dyy_label = QtWidgets.QLabel(self.Module1Frame)
        self.dyy_label.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.dyy_label.setFont(font)
        self.dyy_label.setObjectName("dyy_label")
        self.gridLayout.addWidget(self.dyy_label, 2, 2, 1, 1)
        self.dyy_box = QtWidgets.QTextEdit(self.Module1Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dyy_box.sizePolicy().hasHeightForWidth())
        self.dyy_box.setSizePolicy(sizePolicy)
        self.dyy_box.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.dyy_box.setFont(font)
        self.dyy_box.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.dyy_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dyy_box.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dyy_box.setObjectName("dyy_box")
        self.gridLayout.addWidget(self.dyy_box, 2, 3, 1, 1)
        self.dzz_label = QtWidgets.QLabel(self.Module1Frame)
        self.dzz_label.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.dzz_label.setFont(font)
        self.dzz_label.setObjectName("dzz_label")
        self.gridLayout.addWidget(self.dzz_label, 2, 4, 1, 1)
        self.dz_box = QtWidgets.QTextEdit(self.Module1Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dz_box.sizePolicy().hasHeightForWidth())
        self.dz_box.setSizePolicy(sizePolicy)
        self.dz_box.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.dz_box.setFont(font)
        self.dz_box.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.dz_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dz_box.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dz_box.setObjectName("dz_box")
        self.gridLayout.addWidget(self.dz_box, 2, 5, 1, 1)
        self.s_true_label = QtWidgets.QLabel(self.Module1Frame)
        self.s_true_label.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.s_true_label.setFont(font)
        self.s_true_label.setObjectName("s_true_label")
        self.gridLayout.addWidget(self.s_true_label, 3, 0, 1, 1)

        self.s_true_button = QtWidgets.QToolButton(self.Module1Frame)
        self.s_true_button.setMinimumSize(QtCore.QSize(200, 25))
        self.s_true_button.setMaximumSize(QtCore.QSize(200, 25))
        self.s_true_button.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.s_true_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.s_true_button.setAutoRaise(True)
        self.s_true_button.setObjectName("s_true_button")
        self.gridLayout.addWidget(self.s_true_button, 3, 1, 1, 1)

        self.s_true_button.clicked.connect(self.openFileNameDialog)


        self.n_output_label = QtWidgets.QLabel(self.Module1Frame)
        self.n_output_label.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.n_output_label.setFont(font)
        self.n_output_label.setObjectName("n_output_label")
        self.gridLayout.addWidget(self.n_output_label, 4, 0, 1, 1)
        self.n_output = QtWidgets.QLabel(self.Module1Frame)
        self.n_output.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.n_output.setFont(font)
        self.n_output.setText("")
        self.n_output.setObjectName("n_output")
        self.gridLayout.addWidget(self.n_output, 4, 1, 1, 1)
        self.m_output_label = QtWidgets.QLabel(self.Module1Frame)
        self.m_output_label.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.m_output_label.setFont(font)
        self.m_output_label.setObjectName("m_output_label")
        self.gridLayout.addWidget(self.m_output_label, 4, 2, 1, 1)
        self.m_output = QtWidgets.QLabel(self.Module1Frame)
        self.m_output.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.m_output.setFont(font)
        self.m_output.setText("")
        self.m_output.setObjectName("m_output")
        self.gridLayout.addWidget(self.m_output, 4, 3, 1, 1)
        self.check_mod1 = QtWidgets.QPushButton(self.Module1Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_mod1.sizePolicy().hasHeightForWidth())
        self.check_mod1.setSizePolicy(sizePolicy)
        self.check_mod1.setMinimumSize(QtCore.QSize(130, 20))
        self.check_mod1.setMaximumSize(QtCore.QSize(130, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setKerning(True)
        self.check_mod1.setFont(font)
        self.check_mod1.setAutoDefault(False)
        self.check_mod1.setObjectName("check_mod1")
        self.gridLayout.addWidget(self.check_mod1, 4, 5, 1, 1)
        self.dy_label_2 = QtWidgets.QTextEdit(self.Module1Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dy_label_2.sizePolicy().hasHeightForWidth())
        self.dy_label_2.setSizePolicy(sizePolicy)
        self.dy_label_2.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.dy_label_2.setFont(font)
        self.dy_label_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.dy_label_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dy_label_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dy_label_2.setObjectName("dy_label_2")
        self.gridLayout.addWidget(self.dy_label_2, 3, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.Module1Frame)
        self.label_2.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 2, 1, 1)
        self.fname_output = QtWidgets.QLabel(self.centralwidget)
        self.fname_output.setGeometry(QtCore.QRect(11, 150, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.fname_output.setFont(font)
        self.fname_output.setText("")
        self.fname_output.setObjectName("fname_output")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(11, 311, 300, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.Module1Frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.Module1Frame_2.setGeometry(QtCore.QRect(11, 343, 689, 80))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.Module1Frame_2.setFont(font)
        self.Module1Frame_2.setAutoFillBackground(True)
        self.Module1Frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Module1Frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Module1Frame_2.setObjectName("Module1Frame_2")
        self.forward_model = QtWidgets.QComboBox(self.Module1Frame_2)
        self.forward_model.setGeometry(QtCore.QRect(164, 11, 123, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forward_model.sizePolicy().hasHeightForWidth())
        self.forward_model.setSizePolicy(sizePolicy)
        self.forward_model.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.forward_model.setFont(font)
        self.forward_model.setObjectName("forward_model")
        self.forward_model.addItem("")
        self.forward_model.addItem("")
        self.forward_model.addItem("")
        self.label_16 = QtWidgets.QLabel(self.Module1Frame_2)
        self.label_16.setGeometry(QtCore.QRect(13, 42, 50, 16))
        self.label_16.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_10 = QtWidgets.QLabel(self.Module1Frame_2)
        self.label_10.setGeometry(QtCore.QRect(13, 13, 104, 16))
        self.label_10.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.log_check = QtWidgets.QCheckBox(self.Module1Frame_2)
        self.log_check.setGeometry(QtCore.QRect(605, 14, 19, 18))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.log_check.setFont(font)
        self.log_check.setText("")
        self.log_check.setObjectName("log_check")
        self.label_11 = QtWidgets.QLabel(self.Module1Frame_2)
        self.label_11.setGeometry(QtCore.QRect(530, 13, 25, 16))
        self.label_11.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.source_button = QtWidgets.QToolButton(self.Module1Frame_2)
        self.source_button.setGeometry(QtCore.QRect(90, 42, 200, 25))
        self.source_button.setMinimumSize(QtCore.QSize(200, 25))
        self.source_button.setMaximumSize(QtCore.QSize(200, 25))
        self.source_button.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.source_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.source_button.setAutoRaise(True)
        self.source_button.setObjectName("source_button")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(11, 439, 169, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setObjectName("label_12")
        self.Module1Frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.Module1Frame_3.setGeometry(QtCore.QRect(11, 471, 691, 86))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.Module1Frame_3.setFont(font)
        self.Module1Frame_3.setAutoFillBackground(True)
        self.Module1Frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Module1Frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Module1Frame_3.setObjectName("Module1Frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Module1Frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.zlocs_label = QtWidgets.QTextEdit(self.Module1Frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zlocs_label.sizePolicy().hasHeightForWidth())
        self.zlocs_label.setSizePolicy(sizePolicy)
        self.zlocs_label.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.zlocs_label.setFont(font)
        self.zlocs_label.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.zlocs_label.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.zlocs_label.setObjectName("zlocs_label")
        self.gridLayout_3.addWidget(self.zlocs_label, 1, 5, 1, 1)
        self.ylocs_label = QtWidgets.QTextEdit(self.Module1Frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ylocs_label.sizePolicy().hasHeightForWidth())
        self.ylocs_label.setSizePolicy(sizePolicy)
        self.ylocs_label.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.ylocs_label.setFont(font)
        self.ylocs_label.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ylocs_label.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ylocs_label.setObjectName("ylocs_label")
        self.gridLayout_3.addWidget(self.ylocs_label, 1, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.Module1Frame_3)
        self.label_19.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 4, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.Module1Frame_3)
        self.label_18.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 2, 1, 1)
        self.n_label = QtWidgets.QTextEdit(self.Module1Frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_label.sizePolicy().hasHeightForWidth())
        self.n_label.setSizePolicy(sizePolicy)
        self.n_label.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.n_label.setFont(font)
        self.n_label.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.n_label.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.n_label.setObjectName("n_label")
        self.gridLayout_3.addWidget(self.n_label, 0, 5, 1, 1)
        self.xlocs_label = QtWidgets.QTextEdit(self.Module1Frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xlocs_label.sizePolicy().hasHeightForWidth())
        self.xlocs_label.setSizePolicy(sizePolicy)
        self.xlocs_label.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.xlocs_label.setFont(font)
        self.xlocs_label.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.xlocs_label.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.xlocs_label.setObjectName("xlocs_label")
        self.gridLayout_3.addWidget(self.xlocs_label, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.Module1Frame_3)
        self.label_17.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.Module1Frame_3)
        self.label_14.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.Module1Frame_3)
        self.label_13.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.Obs_button = QtWidgets.QToolButton(self.Module1Frame_3)
        self.Obs_button.setMinimumSize(QtCore.QSize(200, 25))
        self.Obs_button.setMaximumSize(QtCore.QSize(200, 25))
        self.Obs_button.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.Obs_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.Obs_button.setAutoRaise(True)
        self.Obs_button.setObjectName("Obs_button")
        self.gridLayout_3.addWidget(self.Obs_button, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(11, 573, 227, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAutoFillBackground(False)
        self.label_15.setObjectName("label_15")
        self.Module1Frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.Module1Frame_4.setGeometry(QtCore.QRect(11, 605, 691, 156))
        self.Module1Frame_4.setMaximumSize(QtCore.QSize(700, 180))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.Module1Frame_4.setFont(font)
        self.Module1Frame_4.setAutoFillBackground(True)
        self.Module1Frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Module1Frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Module1Frame_4.setObjectName("Module1Frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Module1Frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_20 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_20.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 0, 0, 1, 1)
        self.x_select = QtWidgets.QComboBox(self.Module1Frame_4)
        self.x_select.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.x_select.setFont(font)
        self.x_select.setObjectName("x_select")
        self.x_select.addItem("")
        self.x_select.addItem("")
        self.x_select.addItem("")
        self.gridLayout_4.addWidget(self.x_select, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_21.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 0, 2, 1, 1)
        self.precision_label = QtWidgets.QTextEdit(self.Module1Frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.precision_label.sizePolicy().hasHeightForWidth())
        self.precision_label.setSizePolicy(sizePolicy)
        self.precision_label.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.precision_label.setFont(font)
        self.precision_label.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.precision_label.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.precision_label.setObjectName("precision_label")
        self.gridLayout_4.addWidget(self.precision_label, 0, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_25.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 0, 4, 1, 1)
        self.kernel_box = QtWidgets.QComboBox(self.Module1Frame_4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.kernel_box.setFont(font)
        self.kernel_box.setObjectName("kernel_box")
        self.kernel_box.addItem("")
        self.kernel_box.addItem("")
        self.gridLayout_4.addWidget(self.kernel_box, 0, 5, 1, 2)
        self.label_22 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_22.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 1, 0, 1, 1)
        self.n_pc_label = QtWidgets.QTextEdit(self.Module1Frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_pc_label.sizePolicy().hasHeightForWidth())
        self.n_pc_label.setSizePolicy(sizePolicy)
        self.n_pc_label.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.n_pc_label.setFont(font)
        self.n_pc_label.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.n_pc_label.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.n_pc_label.setObjectName("n_pc_label")
        self.gridLayout_4.addWidget(self.n_pc_label, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_23.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 1, 2, 1, 1)
        self.matvec_box = QtWidgets.QComboBox(self.Module1Frame_4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.matvec_box.setFont(font)
        self.matvec_box.setObjectName("matvec_box")
        self.matvec_box.addItem("")
        self.matvec_box.addItem("")
        self.matvec_box.addItem("")
        self.matvec_box.addItem("")
        self.gridLayout_4.addWidget(self.matvec_box, 1, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_24.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 2, 0, 1, 1)
        self.r_label = QtWidgets.QTextEdit(self.Module1Frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r_label.sizePolicy().hasHeightForWidth())
        self.r_label.setSizePolicy(sizePolicy)
        self.r_label.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.r_label.setFont(font)
        self.r_label.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.r_label.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.r_label.setObjectName("r_label")
        self.gridLayout_4.addWidget(self.r_label, 2, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_26.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 2, 2, 1, 1)
        self.maxiter_label = QtWidgets.QTextEdit(self.Module1Frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxiter_label.sizePolicy().hasHeightForWidth())
        self.maxiter_label.setSizePolicy(sizePolicy)
        self.maxiter_label.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.maxiter_label.setFont(font)
        self.maxiter_label.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.maxiter_label.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.maxiter_label.setObjectName("maxiter_label")
        self.gridLayout_4.addWidget(self.maxiter_label, 2, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_27.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 2, 4, 1, 1)
        self.restol_label = QtWidgets.QTextEdit(self.Module1Frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restol_label.sizePolicy().hasHeightForWidth())
        self.restol_label.setSizePolicy(sizePolicy)
        self.restol_label.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.restol_label.setFont(font)
        self.restol_label.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.restol_label.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.restol_label.setObjectName("restol_label")
        self.gridLayout_4.addWidget(self.restol_label, 2, 5, 1, 2)
        self.label_28 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_28.setMaximumSize(QtCore.QSize(65, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 3, 0, 1, 1)
        self.post_cov_label = QtWidgets.QTextEdit(self.Module1Frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.post_cov_label.sizePolicy().hasHeightForWidth())
        self.post_cov_label.setSizePolicy(sizePolicy)
        self.post_cov_label.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.post_cov_label.setFont(font)
        self.post_cov_label.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.post_cov_label.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.post_cov_label.setObjectName("post_cov_label")
        self.gridLayout_4.addWidget(self.post_cov_label, 3, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_30.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 3, 2, 1, 1)
        self.lm_check = QtWidgets.QCheckBox(self.Module1Frame_4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.lm_check.setFont(font)
        self.lm_check.setText("")
        self.lm_check.setObjectName("lm_check")
        self.gridLayout_4.addWidget(self.lm_check, 3, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_29.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 3, 4, 1, 2)
        self.line_search = QtWidgets.QCheckBox(self.Module1Frame_4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.line_search.setFont(font)
        self.line_search.setText("")
        self.line_search.setObjectName("line_search")
        self.gridLayout_4.addWidget(self.line_search, 3, 6, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 22))
        self.menubar.setObjectName("menubar")
        self.menupyPCGA = QtWidgets.QMenu(self.menubar)
        self.menupyPCGA.setObjectName("menupyPCGA")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionDownload = QtWidgets.QAction(MainWindow)
        self.actionDownload.setObjectName("actionDownload")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.menupyPCGA.addAction(self.actionNew)
        self.menupyPCGA.addAction(self.actionSave)
        self.menupyPCGA.addAction(self.actionDownload)
        self.menupyPCGA.addAction(self.actionImport)
        self.menubar.addAction(self.menupyPCGA.menuAction())

        self.frame = QtWidgets.QWidget(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(760, 30, 651, 511))
        self.frame.setObjectName("frame")
        self.fig = plt.figure()
        self.plotWidget = FigureCanvas(self.fig)
        self.plotWidget.setParent(self.frame)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lx_box, self.ly_box)
        MainWindow.setTabOrder(self.ly_box, self.lz_box)
        MainWindow.setTabOrder(self.lz_box, self.dxx_box)
        MainWindow.setTabOrder(self.dxx_box, self.dyy_box)
        MainWindow.setTabOrder(self.dyy_box, self.dz_box)
        MainWindow.setTabOrder(self.dz_box, self.n_label)
        MainWindow.setTabOrder(self.n_label, self.xlocs_label)
        MainWindow.setTabOrder(self.xlocs_label, self.ylocs_label)
        MainWindow.setTabOrder(self.ylocs_label, self.zlocs_label)
        MainWindow.setTabOrder(self.zlocs_label, self.x_select)
        MainWindow.setTabOrder(self.x_select, self.precision_label)
        MainWindow.setTabOrder(self.precision_label, self.kernel_box)
        MainWindow.setTabOrder(self.kernel_box, self.n_pc_label)
        MainWindow.setTabOrder(self.n_pc_label, self.matvec_box)
        MainWindow.setTabOrder(self.matvec_box, self.r_label)
        MainWindow.setTabOrder(self.r_label, self.maxiter_label)
        MainWindow.setTabOrder(self.maxiter_label, self.restol_label)
        MainWindow.setTabOrder(self.restol_label, self.execute_button)
        MainWindow.setTabOrder(self.execute_button, self.export_settings)
        MainWindow.setTabOrder(self.export_settings, self.import_settings)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.export_settings.setText(_translate("MainWindow", "Export Settings"))
        self.import_settings.setText(_translate("MainWindow", "Import Settings"))
        self.execute_button.setText(_translate("MainWindow", "Execute"))
        self.progress_bar_label.setText(_translate("MainWindow", "Progress Bar"))
        self.fname_label.setText(_translate("MainWindow", "File Name:"))
        self.dimension_label.setText(_translate("MainWindow", "Dimensions:"))
        self.label.setText(_translate("MainWindow", "Module 1: Domain Parameters"))
        self.x0_label.setText(_translate("MainWindow", "x0:"))
        self.x0_box.setPlaceholderText(_translate("MainWindow", "0 ~ any real number"))
        self.y0_label.setText(_translate("MainWindow", "y0:"))
        self.y0_box.setPlaceholderText(_translate("MainWindow", "0 ~ any real number"))
        self.z0_label.setText(_translate("MainWindow", "z0:"))
        self.z0_box.setPlaceholderText(_translate("MainWindow", "0 ~ any real number"))
        self.lx_label.setText(_translate("MainWindow", "Lx:"))
        self.lx_box.setPlaceholderText(_translate("MainWindow", "0 ~ any real number"))
        self.label_4.setText(_translate("MainWindow", "Ly:"))
        self.ly_box.setPlaceholderText(_translate("MainWindow", "0 ~ any real number"))
        self.lz_label.setText(_translate("MainWindow", "Lz:"))
        self.lz_box.setPlaceholderText(_translate("MainWindow", "0 ~ any real number"))
        self.dxx_label.setText(_translate("MainWindow", "dxx:"))
        self.dxx_box.setPlaceholderText(_translate("MainWindow", "0 - 200"))
        self.dyy_label.setText(_translate("MainWindow", "dyy:"))
        self.dyy_box.setPlaceholderText(_translate("MainWindow", "0 - 200"))
        self.dzz_label.setText(_translate("MainWindow", "dzz:"))
        self.dz_box.setPlaceholderText(_translate("MainWindow", "0 - 200"))
        self.s_true_label.setText(_translate("MainWindow", "s_true:"))
        self.s_true_button.setText(_translate("MainWindow", "Click to select file"))
        self.n_output_label.setText(_translate("MainWindow", "N:"))
        self.m_output_label.setText(_translate("MainWindow", "M:"))
        self.check_mod1.setText(_translate("MainWindow", "check values"))
        self.dy_label_2.setPlaceholderText(_translate("MainWindow", "0 - 200"))
        self.label_2.setText(_translate("MainWindow", "s_init:"))
        self.label_8.setText(_translate("MainWindow", "Module 2: Forward Model Parameters"))
        self.forward_model.setItemText(0, _translate("MainWindow", "MODFLOW"))
        self.forward_model.setItemText(1, _translate("MainWindow", "Matrix"))
        self.forward_model.setItemText(2, _translate("MainWindow", "Tough"))
        self.label_16.setText(_translate("MainWindow", "source:"))
        self.label_10.setText(_translate("MainWindow", "forward_model:"))
        self.label_11.setText(_translate("MainWindow", "log:"))
        self.source_button.setText(_translate("MainWindow", "Click to select file"))
        self.label_12.setText(_translate("MainWindow", "Module 3: Observations"))
        self.label_19.setText(_translate("MainWindow", "zlocs:"))
        self.label_18.setText(_translate("MainWindow", "ylocs:"))
        self.label_17.setText(_translate("MainWindow", "xlocs: "))
        self.label_14.setText(_translate("MainWindow", "n:"))
        self.label_13.setText(_translate("MainWindow", "Obs:"))
        self.Obs_button.setText(_translate("MainWindow", "Click to select file"))
        self.label_15.setText(_translate("MainWindow", "Module 4: Inversion Parameters"))
        self.label_20.setText(_translate("MainWindow", "x:"))
        self.x_select.setItemText(0, _translate("MainWindow", "Unit"))
        self.x_select.setItemText(1, _translate("MainWindow", "Constant"))
        self.x_select.setItemText(2, _translate("MainWindow", "Linear"))
        self.label_21.setText(_translate("MainWindow", "precision:"))
        self.label_25.setText(_translate("MainWindow", "kernel:"))
        self.kernel_box.setItemText(0, _translate("MainWindow", "Gaussian"))
        self.kernel_box.setItemText(1, _translate("MainWindow", "Exponential"))
        self.label_22.setText(_translate("MainWindow", "n_pc:"))
        self.label_23.setText(_translate("MainWindow", "matvec:"))
        self.matvec_box.setItemText(0, _translate("MainWindow", "Dense"))
        self.matvec_box.setItemText(1, _translate("MainWindow", "FFT"))
        self.matvec_box.setItemText(2, _translate("MainWindow", "Hmatrix"))
        self.matvec_box.setItemText(3, _translate("MainWindow", "FMM"))
        self.label_24.setText(_translate("MainWindow", "R:"))
        self.label_26.setText(_translate("MainWindow", "maxiter:"))
        self.label_27.setText(_translate("MainWindow", "restol:"))
        self.label_28.setText(_translate("MainWindow", "post_cov:"))
        self.label_30.setText(_translate("MainWindow", "LM:"))
        self.label_29.setText(_translate("MainWindow", "Linesearch:"))
        self.menupyPCGA.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionDownload.setText(_translate("MainWindow", "Download"))
        self.actionImport.setText(_translate("MainWindow", "Import"))



    # function to pop up open file dialog
    def openFileNameDialog(self):
        options = QtWidgets.QFileDialog.Options()
        options |= QtWidgets.QFileDialog.DontUseNativeDialog
        fileName, _ = QtWidgets.QFileDialog.getOpenFileName(self.s_true_button,"QFileDialog.getOpenFileName()", "","All Files (*);;Text Files (*.txt)", options=options)
        if fileName:
            print(fileName)

    def execute(self):
        value_2 = int(self.x0_box.toPlainText())
        value = int(self.lx_box.toPlainText())

        print("values: ", value, value_2)

        self.plot(value, value_2)

    def plot(self, lx, x0):
    # for windows application
        # model domain and discretization
        
        # This is a 1D case, therefore should be used to test the 1D scenario
        
        ####### BEGINNING OF MODULE 1 #################### 

        # M1 parameters are: Lx, Ly, Lz, x0, y0, z0, dx, dy, dz, s_true, s_init

        x0 = x0      # M1: Origin of x dimension 
        Lx = lx   # M1: Total length in the x direction
        dxx = 0.1   # M1: Discretization (cell length) in the x direction, assumes cells of equal size

        # This simulation is 1D, therefore default to y_origin = z_origin = 0, Ly = Lz = 1, dy = dz = 1

        y0 = 0      # M1: Origin of y dimension 
        Ly = 1  # M1: Total length in the y direction
        dyy = 1     # M1: Discretization (cell length) in the y direction, assumes cells of equal size

        z0 = 0      # M1: Origin of y dimension 
        Lz = 1  # M1: Total length in the y direction
        dzz = 1     # M1: Discretization (cell length) in the z direction, assumes cells of equal size

        xmin = np.array([x0]) 
        xmax = np.array([Lx])

        m = int(Lx/dxx + 1) 
        N = np.array([m])

        _translate = QtCore.QCoreApplication.translate

        self.m_output.setText(_translate("MainWindow", str(m)))
        self.n_output.setText(_translate("MainWindow", str(N)))


        dx = np.array([dxx])
        x = np.linspace(xmin, xmax, m)
        pts = np.copy(x)
     

        s_true = np.loadtxt('true.txt') # M1: input for file "true.txt"  

        # s_init, three options (drop down menu) 
        # option 1: user inputs a constant which gets assigned to variable s_constant 

        s_constant = 1          # M1: User selects constant checkbox from drop down, and inputs number in box 
        s_init = s_constant * np.ones((m, 1))

        # option 2: s_init automatically calculated using s_true, if s_true provided
        # # M1: User selects Auto checkbox from drop down, and check is run to see if s_true was provided 
        print(m)
        s_init = np.mean(s_true) * np.ones((m, 1)) #M1 file input or constant input
        # s_init = np.copy(s_true) # you can try with s_true!
     
        
        ### PLOTTING FOR 1D MODULE 1 #############
        
       ## fig = self.frame.plotWidget.add_subplot(100)
        fig = self.fig.add_subplot(111)
        fig.plot(x, s_init,'k-',label='initial')
        fig.plot(x, s_true,'r-',label='true')

       # self.frame.plotWidget.axes.plot(x, s_init,'k-',label='initial')
       # self.frame.plotWidget.axes.plot(x, s_true,'r-',label='true')
        fig.set_title('Pumping history')
        fig.set_xlabel('Time (min)')
        fig.set_ylabel(r'Q ($m^3$/min)')
        fig.legend()


        self.plotWidget.draw()

        #fig.ylabel(r'Q ($m^3$/min)')
        #fig.legend()
        #fig.draw()

        ####### END OF MODULE 1 #################### 

        ####### BEGINNING OF MODULE 3 ##############

        ##xloc = [xmin:10:xmax]

        ##obs = np.loadtxt('obs.txt')

import sys
from PyQt5.QtWidgets import QApplication, QMainWindow

app = QApplication(sys.argv)
window = QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(window)

window.show()
sys.exit(app.exec_())

