# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pypcga-fe-2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget
import matplotlib
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy.io import savemat, loadmat
import numpy as np
import math

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 875)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 100, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.Module1Frame = QtWidgets.QFrame(self.centralwidget)
        self.Module1Frame.setGeometry(QtCore.QRect(70, 130, 561, 101))
        self.Module1Frame.setAutoFillBackground(True)
        self.Module1Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Module1Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Module1Frame.setObjectName("Module1Frame")
        self.label_2 = QtWidgets.QLabel(self.Module1Frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Module1Frame)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 30, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Module1Frame)
        self.label_4.setGeometry(QtCore.QRect(190, 10, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Module1Frame)
        self.label_5.setGeometry(QtCore.QRect(190, 40, 30, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Module1Frame)
        self.label_6.setGeometry(QtCore.QRect(400, 10, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.textEdit_6 = QtWidgets.QTextEdit(self.Module1Frame)
        self.textEdit_6.setGeometry(QtCore.QRect(440, 40, 110, 20))
        self.textEdit_6.setObjectName("textEdit_6")
        self.label_7 = QtWidgets.QLabel(self.Module1Frame)
        self.label_7.setGeometry(QtCore.QRect(400, 40, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.Module1Frame)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.textEdit_7 = QtWidgets.QTextEdit(self.Module1Frame)
        self.textEdit_7.setGeometry(QtCore.QRect(70, 70, 271, 21))
        self.textEdit_7.setObjectName("textEdit_7")
        self.toolButton = QtWidgets.QToolButton(self.Module1Frame)
        self.toolButton.setGeometry(QtCore.QRect(320, 70, 26, 21))
        self.toolButton.setObjectName("toolButton")
        self.pushButton = QtWidgets.QPushButton(self.Module1Frame)
        self.pushButton.setGeometry(QtCore.QRect(440, 70, 121, 32))
        self.pushButton.setObjectName("pushButton")
        self.textEdit_13 = QtWidgets.QTextEdit(self.Module1Frame)
        self.textEdit_13.setGeometry(QtCore.QRect(240, 40, 110, 20))
        self.textEdit_13.setObjectName("textEdit_13")
        self.textEdit_21 = QtWidgets.QTextEdit(self.Module1Frame)
        self.textEdit_21.setGeometry(QtCore.QRect(40, 40, 110, 20))
        self.textEdit_21.setObjectName("textEdit_21")
        self.textEdit_23 = QtWidgets.QTextEdit(self.Module1Frame)
        self.textEdit_23.setGeometry(QtCore.QRect(40, 10, 110, 20))
        self.textEdit_23.setObjectName("textEdit_23")
        self.textEdit_24 = QtWidgets.QTextEdit(self.Module1Frame)
        self.textEdit_24.setGeometry(QtCore.QRect(240, 10, 110, 20))
        self.textEdit_24.setObjectName("textEdit_24")
        self.textEdit_25 = QtWidgets.QTextEdit(self.Module1Frame)
        self.textEdit_25.setGeometry(QtCore.QRect(440, 10, 110, 20))
        self.textEdit_25.setObjectName("textEdit_25")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(70, 240, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setObjectName("label_8")
        self.Module1Frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.Module1Frame_2.setGeometry(QtCore.QRect(70, 270, 561, 71))
        self.Module1Frame_2.setAutoFillBackground(True)
        self.Module1Frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Module1Frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Module1Frame_2.setObjectName("Module1Frame_2")
        self.label_10 = QtWidgets.QLabel(self.Module1Frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.Module1Frame_2)
        self.label_11.setGeometry(QtCore.QRect(400, 10, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_16 = QtWidgets.QLabel(self.Module1Frame_2)
        self.label_16.setGeometry(QtCore.QRect(10, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.textEdit_14 = QtWidgets.QTextEdit(self.Module1Frame_2)
        self.textEdit_14.setGeometry(QtCore.QRect(70, 40, 271, 21))
        self.textEdit_14.setObjectName("textEdit_14")
        self.comboBox = QtWidgets.QComboBox(self.Module1Frame_2)
        self.comboBox.setGeometry(QtCore.QRect(120, 10, 141, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.checkBox = QtWidgets.QCheckBox(self.Module1Frame_2)
        self.checkBox.setGeometry(QtCore.QRect(440, 10, 31, 20))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.toolButton_2 = QtWidgets.QToolButton(self.Module1Frame_2)
        self.toolButton_2.setGeometry(QtCore.QRect(320, 40, 26, 21))
        self.toolButton_2.setObjectName("toolButton_2")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(70, 350, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setObjectName("label_12")
        self.Module1Frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.Module1Frame_3.setGeometry(QtCore.QRect(70, 380, 561, 71))
        self.Module1Frame_3.setAutoFillBackground(True)
        self.Module1Frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Module1Frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Module1Frame_3.setObjectName("Module1Frame_3")
        self.label_13 = QtWidgets.QLabel(self.Module1Frame_3)
        self.label_13.setGeometry(QtCore.QRect(20, 10, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.Module1Frame_3)
        self.label_14.setGeometry(QtCore.QRect(410, 10, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_17 = QtWidgets.QLabel(self.Module1Frame_3)
        self.label_17.setGeometry(QtCore.QRect(10, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.textEdit_8 = QtWidgets.QTextEdit(self.Module1Frame_3)
        self.textEdit_8.setGeometry(QtCore.QRect(60, 10, 281, 21))
        self.textEdit_8.setObjectName("textEdit_8")
        self.textEdit_9 = QtWidgets.QTextEdit(self.Module1Frame_3)
        self.textEdit_9.setGeometry(QtCore.QRect(440, 10, 111, 21))
        self.textEdit_9.setObjectName("textEdit_9")
        self.toolButton_4 = QtWidgets.QToolButton(self.Module1Frame_3)
        self.toolButton_4.setGeometry(QtCore.QRect(320, 10, 26, 22))
        self.toolButton_4.setObjectName("toolButton_4")
        self.label_18 = QtWidgets.QLabel(self.Module1Frame_3)
        self.label_18.setGeometry(QtCore.QRect(200, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.Module1Frame_3)
        self.label_19.setGeometry(QtCore.QRect(380, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.textEdit_11 = QtWidgets.QTextEdit(self.Module1Frame_3)
        self.textEdit_11.setGeometry(QtCore.QRect(440, 40, 111, 21))
        self.textEdit_11.setObjectName("textEdit_11")
        self.textEdit_12 = QtWidgets.QTextEdit(self.Module1Frame_3)
        self.textEdit_12.setGeometry(QtCore.QRect(240, 40, 111, 21))
        self.textEdit_12.setObjectName("textEdit_12")
        self.textEdit_10 = QtWidgets.QTextEdit(self.Module1Frame_3)
        self.textEdit_10.setGeometry(QtCore.QRect(50, 40, 111, 21))
        self.textEdit_10.setObjectName("textEdit_10")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(70, 460, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setAutoFillBackground(False)
        self.label_15.setObjectName("label_15")
        self.Module1Frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.Module1Frame_4.setGeometry(QtCore.QRect(70, 490, 561, 131))
        self.Module1Frame_4.setAutoFillBackground(True)
        self.Module1Frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Module1Frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Module1Frame_4.setObjectName("Module1Frame_4")
        self.label_20 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_20.setGeometry(QtCore.QRect(30, 10, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_21.setGeometry(QtCore.QRect(170, 10, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.textEdit_15 = QtWidgets.QTextEdit(self.Module1Frame_4)
        self.textEdit_15.setGeometry(QtCore.QRect(240, 10, 111, 21))
        self.textEdit_15.setObjectName("textEdit_15")
        self.comboBox_2 = QtWidgets.QComboBox(self.Module1Frame_4)
        self.comboBox_2.setGeometry(QtCore.QRect(50, 7, 81, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_25 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_25.setGeometry(QtCore.QRect(370, 10, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.comboBox_3 = QtWidgets.QComboBox(self.Module1Frame_4)
        self.comboBox_3.setGeometry(QtCore.QRect(420, 7, 121, 26))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_22 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_22.setGeometry(QtCore.QRect(30, 40, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.textEdit_16 = QtWidgets.QTextEdit(self.Module1Frame_4)
        self.textEdit_16.setGeometry(QtCore.QRect(70, 40, 41, 21))
        self.textEdit_16.setObjectName("textEdit_16")
        self.label_23 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_23.setGeometry(QtCore.QRect(180, 40, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_24.setGeometry(QtCore.QRect(30, 70, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.textEdit_18 = QtWidgets.QTextEdit(self.Module1Frame_4)
        self.textEdit_18.setGeometry(QtCore.QRect(70, 70, 41, 21))
        self.textEdit_18.setObjectName("textEdit_18")
        self.label_26 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_26.setGeometry(QtCore.QRect(210, 70, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.textEdit_19 = QtWidgets.QTextEdit(self.Module1Frame_4)
        self.textEdit_19.setGeometry(QtCore.QRect(270, 70, 51, 21))
        self.textEdit_19.setObjectName("textEdit_19")
        self.label_27 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_27.setGeometry(QtCore.QRect(400, 70, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.textEdit_20 = QtWidgets.QTextEdit(self.Module1Frame_4)
        self.textEdit_20.setGeometry(QtCore.QRect(450, 70, 51, 21))
        self.textEdit_20.setObjectName("textEdit_20")
        self.label_28 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_28.setGeometry(QtCore.QRect(30, 100, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_29.setGeometry(QtCore.QRect(390, 101, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.Module1Frame_4)
        self.label_30.setGeometry(QtCore.QRect(220, 102, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.checkBox_4 = QtWidgets.QCheckBox(self.Module1Frame_4)
        self.checkBox_4.setGeometry(QtCore.QRect(480, 100, 31, 20))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_3 = QtWidgets.QCheckBox(self.Module1Frame_4)
        self.checkBox_3.setGeometry(QtCore.QRect(260, 100, 31, 20))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(self.Module1Frame_4)
        self.comboBox_4.setGeometry(QtCore.QRect(240, 40, 121, 26))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.textEdit_22 = QtWidgets.QTextEdit(self.Module1Frame_4)
        self.textEdit_22.setGeometry(QtCore.QRect(100, 100, 51, 21))
        self.textEdit_22.setObjectName("textEdit_22")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 630, 121, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.execute)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 630, 121, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 630, 121, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(70, 10, 81, 21))
        self.label_31.setObjectName("label_31")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(70, 70, 521, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(70, 50, 81, 20))
        self.label_32.setObjectName("label_32")


        self.frame = QtWidgets.QWidget(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(760, 30, 651, 511))
        self.frame.setObjectName("frame")
        self.fig = plt.figure()
        self.plotWidget = FigureCanvas(self.fig)
        self.plotWidget.setParent(self.frame)

        #self.frame.addWidget(self.frame.plotWidget)
        #self.plotWidget.move(400, 100)


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 22))
        self.menubar.setObjectName("menubar")
        self.menupyPCGA = QtWidgets.QMenu(self.menubar)
        self.menupyPCGA.setObjectName("menupyPCGA")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionDownload = QtWidgets.QAction(MainWindow)
        self.actionDownload.setObjectName("actionDownload")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.menupyPCGA.addAction(self.actionNew)
        self.menupyPCGA.addAction(self.actionSave)
        self.menupyPCGA.addAction(self.actionDownload)
        self.menupyPCGA.addAction(self.actionImport)
        self.menubar.addAction(self.menupyPCGA.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Module 1: Domain Parameters"))
        self.label_2.setText(_translate("MainWindow", "Lx:"))
        self.label_3.setText(_translate("MainWindow", "dx:"))
        self.label_4.setText(_translate("MainWindow", "Ly:"))
        self.label_5.setText(_translate("MainWindow", "dy:"))
        self.label_6.setText(_translate("MainWindow", "Lz:"))
        self.label_7.setText(_translate("MainWindow", "dz:"))
        self.label_9.setText(_translate("MainWindow", "s_true:"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.pushButton.setText(_translate("MainWindow", "check values"))
        self.label_8.setText(_translate("MainWindow", "Module 2: Forward Model Parameters"))
        self.label_10.setText(_translate("MainWindow", "forward_model:"))
        self.label_11.setText(_translate("MainWindow", "log:"))
        self.label_16.setText(_translate("MainWindow", "source:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "MODFLOW"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Matrix"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Tough"))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.label_12.setText(_translate("MainWindow", "Module 3: Observations"))
        self.label_13.setText(_translate("MainWindow", "Obs:"))
        self.label_14.setText(_translate("MainWindow", "n:"))
        self.label_17.setText(_translate("MainWindow", "xlocs: "))
        self.toolButton_4.setText(_translate("MainWindow", "..."))
        self.label_18.setText(_translate("MainWindow", "ylocs:"))
        self.label_19.setText(_translate("MainWindow", "zlocs:"))
        self.label_15.setText(_translate("MainWindow", "Module 4: Inversion Parameters"))
        self.label_20.setText(_translate("MainWindow", "x:"))
        self.label_21.setText(_translate("MainWindow", "precision:"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Unit"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Constant"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Linear"))
        self.label_25.setText(_translate("MainWindow", "kernel:"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Gaussian"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Exponential"))
        self.label_22.setText(_translate("MainWindow", "n_pc:"))
        self.label_23.setText(_translate("MainWindow", "matvec:"))
        self.label_24.setText(_translate("MainWindow", "R:"))
        self.label_26.setText(_translate("MainWindow", "maxiter:"))
        self.label_27.setText(_translate("MainWindow", "restol:"))
        self.label_28.setText(_translate("MainWindow", "post_cov:"))
        self.label_29.setText(_translate("MainWindow", "Linesearch:"))
        self.label_30.setText(_translate("MainWindow", "LM:"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Dense"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "FFT"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Hmatrix"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "FMM"))
        self.pushButton_2.setText(_translate("MainWindow", "Execute"))
        self.pushButton_3.setText(_translate("MainWindow", "Export Settings"))
        self.pushButton_4.setText(_translate("MainWindow", "Import Settings"))
        self.label_31.setText(_translate("MainWindow", "File Name:"))
        self.label_32.setText(_translate("MainWindow", "Progress Bar"))
        self.menupyPCGA.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionDownload.setText(_translate("MainWindow", "Download"))
        self.actionImport.setText(_translate("MainWindow", "Import"))


    def execute(self):
        value = int(self.textEdit_23.toPlainText())
        value_2 = int(self.textEdit_21.toPlainText())

        print("values: ", value, value_2)
        if value != 1000:
            print("incorrect value, please input 1000 for Lx.\n")
        elif value_2 != 0:
            print("incorrect value, please input 0 for dx.\n")
        else:
            self.plot(value, value_2)

    def plot(self, lx, dx):
    # for windows application
        # model domain and discretization
        
        # This is a 1D case, therefore should be used to test the 1D scenario
        
        ####### BEGINNING OF MODULE 1 #################### 

        # M1 parameters are: Lx, Ly, Lz, x0, y0, z0, dx, dy, dz, s_true, s_init

        x0 = dx      # M1: Origin of x dimension 
        Lx = lx   # M1: Total length in the x direction
        dxx = 0.1   # M1: Discretization (cell length) in the x direction, assumes cells of equal size

        # This simulation is 1D, therefore default to y_origin = z_origin = 0, Ly = Lz = 1, dy = dz = 1

        y0 = 0      # M1: Origin of y dimension 
        Ly = 1  # M1: Total length in the y direction
        dyy = 1     # M1: Discretization (cell length) in the y direction, assumes cells of equal size

        z0 = 0      # M1: Origin of y dimension 
        Lz = 1  # M1: Total length in the y direction
        dzz = 1     # M1: Discretization (cell length) in the z direction, assumes cells of equal size

        xmin = np.array([x0]) 
        xmax = np.array([Lx])
        m= int(Lx/dxx + 1) 
        N = np.array([m])
        dx = np.array([dxx])
        x = np.linspace(xmin, xmax, m)
        pts = np.copy(x)
     

        s_true = np.loadtxt('true.txt') # M1: input for file "true.txt"  

        # s_init, three options (drop down menu) 
        # option 1: user inputs a constant which gets assigned to variable s_constant 

        s_constant = 1          # M1: User selects constant checkbox from drop down, and inputs number in box 
        s_init = s_constant * np.ones((m, 1))

        # option 2: s_init automatically calculated using s_true, if s_true provided
        # # M1: User selects Auto checkbox from drop down, and check is run to see if s_true was provided 
        print(m)
        s_init = np.mean(s_true) * np.ones((m, 1)) #M1 file input or constant input
        # s_init = np.copy(s_true) # you can try with s_true!
     
        
        ### PLOTTING FOR 1D MODULE 1 #############
        
       ## fig = self.frame.plotWidget.add_subplot(100)
        fig = self.fig.add_subplot(111)
        fig.plot(x, s_init,'k-',label='initial')
        fig.plot(x, s_true,'r-',label='true')

       # self.frame.plotWidget.axes.plot(x, s_init,'k-',label='initial')
       # self.frame.plotWidget.axes.plot(x, s_true,'r-',label='true')
        fig.set_title('Pumping history')
        fig.set_xlabel('Time (min)')
        fig.set_ylabel(r'Q ($m^3$/min)')
        fig.legend()


        self.plotWidget.draw()

        #fig.ylabel(r'Q ($m^3$/min)')
        #fig.legend()
        #fig.draw()

        ####### END OF MODULE 1 #################### 

import sys
from PyQt5.QtWidgets import QApplication, QMainWindow

app = QApplication(sys.argv)
window = QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(window)

window.show()
sys.exit(app.exec_())




